/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.*;

public class App {
    public static void main(String[] args) {
        JSONArray students = getStudents();

        HashMap<String, Integer> solution1Map = new HashMap<>();
        solution1Map.put("total", students.size());
        JSONObject solution1 = new JSONObject(solution1Map);

        createAndWriteFile("problem_1.json", solution1.toJSONString());

        ArrayList<Long> inactiveUserIds = new ArrayList<>();
        for (int i = 0; i < students.size(); i++) {
            JSONObject student = (JSONObject) students.get(i);

            String studentStatus = (String) student.get("status");
            if(studentStatus.equals("active")) continue;

            long studentId = (Long) student.get("customer_id");
            inactiveUserIds.add(studentId);
        }

        inactiveUserIds.sort(Comparator.naturalOrder());

        JSONArray solution2 = new JSONArray();
        for (int index = 0; index < inactiveUserIds.size(); index++) {
            solution2.add(inactiveUserIds.get(index));
        }
        createAndWriteFile("problem_2.json", solution2.toJSONString());
    }
    private static JSONArray getStudents() {
        try {
            FileReader fileReader = new FileReader("/home/programmers/project/data/input/customer.json");
            JSONArray students = (JSONArray)new JSONParser().parse(fileReader);
            return students;
        } catch(FileNotFoundException e) {
            e.printStackTrace();
            throw new RuntimeException("파일을 읽어오는데 실패했습니다.");
        } catch(Exception e) {
            e.printStackTrace();
            throw new RuntimeException("파일을 파싱하는데 실패했습니다.");
        }
    }

    private static void createAndWriteFile(String filename, String content) {

        File file = new File("/home/programmers/project/data/output/" + filename);
        try {
            boolean isCreated = file.createNewFile();
            if(!isCreated) {
                throw new RuntimeException("이미 동일한 파일이 존재합니다.");
            }
        } catch (IOException e) {
            e.printStackTrace();
            throw new RuntimeException("새로운 파일을 생서하는데 실패했습니다.");
        }

        try {
            FileWriter fileWriter = new FileWriter(file);
            fileWriter.write(content);
			fileWriter.flush();
			fileWriter.close();
        } catch(IOException e) {
            e.printStackTrace();
            throw new RuntimeException("JSON 객체를 출력하는데 실패했습니다.");
        }
    }
    
}
